### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by LoveqLRC** [JammyR/PDF_Demo#3]
``` 
java.lang.NullPointerException: Attempt to invoke interface method 'android.view.View android.widget.Adapter.getView(int, android.view.View, android.view.ViewGroup)' on a null object reference
                                                                                at com.artifex.mupdf.ReaderView.getOrCreateChild(ReaderView.java:498)
                                                                                at com.artifex.mupdf.ReaderView.onLayout(ReaderView.java:397)
                                                                                at android.view.View.layout(View.java:16987)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5550)
                                                                                at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                                at android.view.View.layout(View.java:16987)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5550)
                                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                at android.view.View.layout(View.java:16987)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5550)
                                                                                at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                                at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                                at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                                at android.view.View.layout(View.java:16987)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5550)
                                                                                at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                                at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                                at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2744)
                                                                                at android.view.View.layout(View.java:16987)
                                                                                at android.view.ViewGroup.layout(ViewGroup.java:5550)
                                                                                at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2513)
                                                                                at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2174)
                                                                                at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1268)
                                                                                at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6638)
                                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:926)
                                                                                at android.view.Choreographer.doCallbacks(Choreographer.java:717)
                                                                                at android.view.Choreographer.doFrame(Choreographer.java:652)
                                                                                at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:912)
                                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5669)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by LonelyPluto** [comment]
I had the same problem.Have you solved it?

**Comment by ichikawa-itbook** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
ny911lai, @Shirley2068, @mikeluck, @henryychew, @xDaWenXi, @cocolord, @yuqikai, @BA3000, @lcstudio, @DankeGott, @crazyivanz, @tanwencn, @firebullwang, @kingsanimal, @zgzjyywm, @zhaowei11594, @DarkPotatoooooo, @johnnymillergh, @twpony, @0xUniko, @chwei2ch, @felixice, @nakahaa, @CCzzsd, @20111564, @fangtongen, @HaojieYuan, @isghost, @kinoko-he, @liwy666, @acexyf, @nexsys, @kirineko, @iericwei, @yonghuihui, @aquestionx, @ericwannn, @benno0810, @JasonZhao001, @chaosink, @hj456992, @WindsongZ, @mengwox, @WenyongYe, @lubinszARM, @catror, @AhnanWong, @h521822, @clovery, @xdehuan
